apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metalb-ippool
  namespace: metallb-system
spec:
  addresses:
    - 172.18.255.200-172.18.255.250
  autoAssign: true
  avoidBuggyIPs: false
