---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    run: streamer
  name: streamer-cm
data:
  http.conf: |
    server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        add_header 'Access-Control-Allow-Origin' '*';

        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
        # First attempt to serve request as file, then
        # as directory, then fall back to displaying a 404.
        try_files $uri $uri/ =404;
        }
    }

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    run: streamer
  name: streamer-videos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi