---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: database-service
  name: database-service 
spec:
  selector:
    run: database
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
