---
apiVersion: v1
kind: Service
metadata:
  name: streamer-service
  labels:
    app: streamer
spec:
  # type: NodePort
  type: LoadBalancer
  selector:
    run: streamer
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30010
      protocol: TCP