---
apiVersion: v1
kind: Service
metadata:
  name: streamer-service
spec:
  # type: NodePort
  type: LoadBalancer
  selector:
    run: streamer
  ports:
    - port: 80
      targetPort: 80
      # nodePort: 30010