---
- name: Run the Ginflix application on the Telecom remote server
  hosts: telecom
  gather_facts: false
  become: false

  tasks:
    - name: Get the GitHub repository
      command: |
        cd ~
        git clone https://github.com/gara2000/vod-service.git
    
    - name: Create the K8s cluster
      command: |
        cd ~/vod-service
        make create

    - name: Start the application
      command: |
        cd ~/vod-service
        make start

    - name: Copy the video inside the streamer
      command: |
        cd ~/vod-service
        make copy